### ISSUE TITLE
Train Result Error

### ISSUE THREAD

**Issue by xiangwf** [rajarshd/ChainsofReasoning#10]
When I run this program on my Ubuntu 18.04,and I set the global varieties by not using GPU,and finally I find this output:    
Iter: 2
**avg loss in epoch = nan
total elapsed = 0.885171
time per batch = inf	
examples/sec = 0.000000**	
I don't know why

**Comment by rajarshd** [comment]
Hi. Unfortunately, I am unable to maintain this lua codebase anymore. However I am working on a pytorch re-implmentation which I should be releasing soon. Sorry for any inconvenience.

**Comment by xiangwf** [comment]
Can you send me the site when you finish your codes? Actually， I’m not familiar with lua! For me ,maybe it's a good news! HAHA
