### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by spacewalk01** [rajarshd/ChainsofReasoning#11]
Hi, thank you for your code, I want to know if you performed link prediction tasks for the evaluation. 
For each test entity pair (h, r, t) in WebClue test dataset, you predict (h, r, ?) where you put all entities in place of ? such that:
     predict(h, r, e1)
     predict(h, r, e2)
     ...
     predict(h, r, en)
Then, compute Average Precision for (h, r, ?)

Is it correct?

**Comment by AKBCSemanticParsingSurvey** [comment]
I think that sounds right.

**Comment by rajarshd** [comment]
I think that sounds right!
