### ISSUE TITLE
error loading module 'Util' from file

### ISSUE THREAD

**Issue by xiaoxiaocaoddl** [rajarshd/ChainsofReasoning#13]
hello, when I run the movie_data_format.sh, I met a problem about loading module 'Util' from the folder, I don't know how it happend. I have tried searched answers in Google but found no useful information. I use python2.7 and lua5.1,here is error:
Missed entity pair count 0
train
converting train to torch files
output/train/train.txt.10.int
/home/zju/lkw/lkwenv1/torch/install/bin/lua: ...w/lkwenv1/torch/install/share/lua/5.1/trepl/init.lua:389: error loading module 'Util' from file './Util.lua':
        ./Util.lua:2: unexpected symbol near '#'
stack traceback:
        [C]: in function 'error'
        ...w/lkwenv1/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
        int2torch.lua:4: in main chunk
        [C]: in function 'dofile'
        .../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: ?
int2torch failed!
Failed for relation
output/train/train.txt.11.int
/home/zju/lkw/lkwenv1/torch/install/bin/lua: ...w/lkwenv1/torch/install/share/lua/5.1/trepl/init.lua:389: error loading module 'Util' from file './Util.lua':
        ./Util.lua:2: unexpected symbol near '#'
stack traceback:
        [C]: in function 'error'
        ...w/lkwenv1/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
        int2torch.lua:4: in main chunk
        [C]: in function 'dofile'
        .../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: ?
int2torch failed!
Failed for relation
output/train/train.txt.12.int
/home/zju/lkw/lkwenv1/torch/install/bin/lua: ...w/lkwenv1/torch/install/share/lua/5.1/trepl/init.lua:389: error loading module 'Util' from file './Util.lua':
        ./Util.lua:2: unexpected symbol near '#'
stack traceback:
        [C]: in function 'error'
        ...w/lkwenv1/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
        int2torch.lua:4: in main chunk
        [C]: in function 'dofile'
        .../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: ?
int2torch failed!
Failed for relation
output/train/train.txt.13.int
/home/zju/lkw/lkwenv1/torch/install/bin/lua: ...w/lkwenv1/torch/install/share/lua/5.1/trepl/init.lua:389: error loading module 'Util' from file './Util.lua':
        ./Util.lua:2: unexpected symbol near '#'
stack traceback:
        [C]: in function 'error'
        ...w/lkwenv1/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
        int2torch.lua:4: in main chunk
        [C]: in function 'dofile'
        .../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: ?
int2torch failed!
Failed for relation
output/train/train.txt.14.int
/home/zju/lkw/lkwenv1/torch/install/bin/lua: ...w/lkwenv1/torch/install/share/lua/5.1/trepl/init.lua:389: error loading module 'Util' from file './Util.lua':
        ./Util.lua:2: unexpected symbol near '#'
stack traceback:
        [C]: in function 'error'
        ...w/lkwenv1/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
        int2torch.lua:4: in main chunk
        [C]: in function 'dofile'
        .../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: ?
int2torch failed!
Failed for relation
output/train/train.txt.15.int
/home/zju/lkw/lkwenv1/torch/install/bin/lua: ...w/lkwenv1/torch/install/share/lua/5.1/trepl/init.lua:389: error loading module 'Util' from file './Util.lua':
        ./Util.lua:2: unexpected symbol near '#'
stack traceback:
        [C]: in function 'error'
        ...w/lkwenv1/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
        int2torch.lua:4: in main chunk
        [C]: in function 'dofile'
        .../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: ?
int2torch failed!
Failed for relation
......
Hope to hear from you！Have a good day.

**Comment by zhuqiannan093** [comment]
I also have the problem, have you solved it?
