### ISSUE TITLE
Total num batches 0

### ISSUE THREAD

**Issue by svakulenk0** [rajarshd/ChainsofReasoning#3]
Whoops! Just noticed that it is actually not training but only iterating:

 /bin/bash train.sh ./config.sh
...
Making a pass of the data to count the batches	
Total num batches 0	

Iter: 1
avg loss in epoch = nan
total elapsed = 0.000831
time per batch = inf	
examples/sec = 0.000000	
saving to results/lse/2017-02-10-16-05-43/_architecture_structure_address/model-1
...
Iter: 20
avg loss in epoch = nan
total elapsed = 0.379223
time per batch = inf	
examples/sec = 0.000000	

Could you check whether it is running like this on your side? Maybe I broke something on the way already :)

**Comment by rajarshd** [comment]
I will try to fix this in the coming weekend :)

**Comment by rajarshd** [comment]
Actually can you cat your config.sh below?

**Comment by svakulenk0** [comment]
Thank you! 
You already merged my config.sh into your master branch https://github.com/rajarshd/ChainsofReasoning/blob/master/run_scripts/config.sh

**Comment by computerMoMo** [comment]
I met the same problem, is this problem solved?

**Comment by spacewalk01** [comment]
I also got the same error. Anyone solved it? Thank you
