### ISSUE TITLE
Test issues

### ISSUE THREAD

**Issue by verazuo** [rajarshd/ChainsofReasoning#4]
Hello，I have studied your code for a long time, but just now I found out that it seems you didn't push your test code here ?
I have already run out the module 0-20, could you please told me how to recurrence your results in your [paper](https://arxiv.org/abs/1607.01426)?
And the link on this repository is linked to `the  5 Jul 2016 (v1)`version, do you really mean that? Or just forgot to update it to the v2 version?
![image](https://cloud.githubusercontent.com/assets/16172194/24350878/75872044-1316-11e7-9122-d57c65860ca5.png)

This is really important for my group, thanks for your answer.

**Comment by rajarshd** [comment]
I am fixing the link. Thanks!, Which test are you referring to. Could you be a little more clear?

**Comment by verazuo** [comment]
After the last 3lines of code in`OneModule.lua`
```lua
params.learningRate = params.pretrainLearningRate	--之前的训练学习率
optimizer = MyOptimizer(training_net,training_net,criterion,trainingOptions,optInfo,params.rnnType) 
optimizer:train(trainBatcher)
```
I got the results which's tree is like .
```
./_architecture_structure_address/
|    config.txt
|    log.txt
|    model-0
|    model-1
|    model-2
|    ... ...
|    model-18
|    model-19
|    model-20
```
But as you can see, the `model-x` files have no filetype, and after reading your code, I found out the code have already finished trainning process.In my opinion, the next process may be test right ?
I found out this[ URL ](http://people.cs.umass.edu/~rajarshi/paths.html)in your paper which shows the results of your research, but how could I get the same results? Or in other words, how could I get this below test result data in your paper with this `model-x`?
![1](https://cloud.githubusercontent.com/assets/16172194/24384331/ac8ba612-1395-11e7-90fe-657bb412f11c.jpg)

**Comment by rajarshd** [comment]
I think I understand your question now. Yes you are correct, the next step would be testing. The evaluation criteria is Mean Avg. Precision and I use the offical trec_eval scripts to do it (http://trec.nist.gov/trec_eval/). To get the scores on the dev/test data, I have a separate script which loads the saved model and does a forward pass (I am sorry, this part is sloppy). I will checkin that code. The trec eval script should give you the avg. MAP score. Let me know how it goes. I am keeping this issue open till you are able to run it.
