### ISSUE TITLE
train-trainBatcher:getBatch()

### ISSUE THREAD

**Issue by strawber** [rajarshd/ChainsofReasoning#5]
Hello, when I study your code ,I find some question in train.can you give me some solution?
In `Myptimizer.lua` ,  I find this code dont calculate the err and Update the model When I use CPU to train the model.
   At `function MyOptimizer:train(trainBatcher)`,the trainBatcher will do getBatcher() as ` local minibatch_targets,minibatch_inputs,num, classId = trainBatcher:getBatch()`, 
   But when I study the getBatcher function in `BatcherFileList.lua` ，I find this code just give the useCUDA's method and do nothing when use CPU  .Therfore, it will get  nil, so that the `while` will break before update parameters. 
So，I'm really confused that  how to train  our model when use CPU.   I'm not sure if I understand it wrong, can you tell me?

**Comment by rajarshd** [comment]
Hi. Unfortunately, I am unable to maintain this lua codebase anymore. However I am working on a pytorch re-implmentation which I should be releasing soon. Sorry for any inconvenience.
