### ISSUE TITLE
Could not get the reported MAP score.

### ISSUE THREAD

**Issue by 0532yangyang** [rajarshd/ChainsofReasoning#6]
Hi Rajarshd, thanks for sharing the eval code. 
I have tried running the latest code, but find the result a little weird.  I wrote a script and calculated MAP based on the `test.scores` files generated with the latest model (e.g. test.scores.model-20) of the 46 relations, and only got  MAP=0.39 on test set. Is there any extra work to be done to get the right result, or any place that I should pay attention to?
Additionally, there are many different variants of the proposed model in your paper, but which one corresponds to the default config in the code?
![image](https://cloud.githubusercontent.com/assets/3928691/24995348/189d6890-2061-11e7-8998-7979d6f900b9.png)

**Comment by rajarshd** [comment]
Hi, thanks for running the code. I will look into this later tonight, but my prime suspect is a mismatch in the dataset (I apologize in advance if this is the case). I will have to work with my sysadmin to release the correct dataset. Also is this the score tuned wrt the dev set?

**Comment by 0532yangyang** [comment]
Thanks for the the quick reply.
I made the evaluation on both test and dev set, and the results are pretty alike. 
Details:
![image](https://cloud.githubusercontent.com/assets/3928691/25031516/0764c9b6-2100-11e7-85f5-7be9362a1150.png)

**Comment by 0532yangyang** [comment]
Hi, rajarshd, could you send me an original version of the dataset (the one used in your paper)?

**Comment by rajarshd** [comment]
Hey, sorry for being late. I haven't found time to look into this. But I will this weekend. Also this doesn't look like a code issue yet, so can you please email me instead (rajarshi@cs.umass.edu)

I am closing this issue for now, and we can reopen it if there needs to be a code fix. Thanks!

**Comment by jane2nemu** [comment]
Hi, yangyang @0532yangyang , have you finally got the MAP as reported? I'm stuck working here for a while, it would be a great help if you could contact me via email.
