### ISSUE TITLE
run examples failed and find some bug in "BatcherFileList:getBatch"

### ISSUE THREAD

**Issue by computerMoMo** [rajarshd/ChainsofReasoning#9]
Hi, when I run the example data with the demo config, it failed. It seems like that there are some bugs in "MyOptimizer.lua" line 181. 
By the way I don't use GPU. And it always return nil in "BatcherFileList:getBatch()", I fix that bug and rerun the example data with the demo config , it failed.

>  /home/momo/torch/install/share/lua/5.1/nn/Select.lua:11: attempt to compare nil with number
> stack traceback:
> 	/home/momo/torch/install/share/lua/5.1/nn/Select.lua:11: in function </home/momo/torch/install/share/lua/5.1/nn/Select.lua:9>
> 	[C]: in function 'xpcall'
> 	/home/momo/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
> 	/home/momo/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
> 	../model/optimizer/MyOptimizer.lua:183: in function 'opfunc'
> 	/home/momo/torch/install/share/lua/5.1/optim/adam.lua:37: in function 'optimMethod'
> 	../model/optimizer/MyOptimizer.lua:212: in function 'trainBatch'
> 	../model/optimizer/MyOptimizer.lua:133: in function <../model/optimizer/MyOptimizer.lua:90>
> 	..//model/OneModel.lua:412: in main chunk
> 	[C]: in function 'dofile'
> 	...momo/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
> 	[C]: at 0x00405d50
> 
> WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
> stack traceback:
> 	[C]: in function 'error'
> 	/home/momo/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
> 	/home/momo/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
> 	../model/optimizer/MyOptimizer.lua:183: in function 'opfunc'
> 	/home/momo/torch/install/share/lua/5.1/optim/adam.lua:37: in function 'optimMethod'
> 	../model/optimizer/MyOptimizer.lua:212: in function 'trainBatch'
> 	../model/optimizer/MyOptimizer.lua:133: in function <../model/optimizer/MyOptimizer.lua:90>
> 	..//model/OneModel.lua:412: in main chunk
> 	[C]: in function 'dofile'
> 	...momo/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
> 	[C]: at 0x00405d50
>

**Comment by computerMoMo** [comment]
When I run the code on GPU, the same error occurs. 

> Making a pass of the data to count the batches
> Total num batches 2
> /root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/nn/Container.lua:67:
> In 2 module of nn.Sequential:
> /root/torch/install/share/lua/5.1/nn/Select.lua:11: attempt to compare nil with number
> stack traceback:
>         /root/torch/install/share/lua/5.1/nn/Select.lua:11: in function </root/torch/install/share/lua/5.1/nn/Select.lua:9>
>         [C]: in function 'xpcall'
>         /root/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
>         /root/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
>         ../model/optimizer/MyOptimizer.lua:181: in function 'opfunc'
>         /root/torch/install/share/lua/5.1/optim/adam.lua:37: in function 'optimMethod'
>         ../model/optimizer/MyOptimizer.lua:209: in function 'trainBatch'
>         ../model/optimizer/MyOptimizer.lua:132: in function <../model/optimizer/MyOptimizer.lua:90>
>         ..//model/OneModel.lua:409: in main chunk
>         [C]: in function 'dofile'
>         /root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
>         [C]: at 0x00405d50
> 
> WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
> stack traceback:
>         [C]: in function 'error'
>         /root/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
>         /root/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
>         ../model/optimizer/MyOptimizer.lua:181: in function 'opfunc'
>         /root/torch/install/share/lua/5.1/optim/adam.lua:37: in function 'optimMethod'
>         ../model/optimizer/MyOptimizer.lua:209: in function 'trainBatch'
>         ../model/optimizer/MyOptimizer.lua:132: in function <../model/optimizer/MyOptimizer.lua:90>
>         ..//model/OneModel.lua:409: in main chunk
>         [C]: in function 'dofile'
>         /root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
>         [C]: at 0x00405d50

**Comment by Yrettop** [comment]
> Hi, when I run the example data with the demo config, it failed. It seems like that there are some bugs in "MyOptimizer.lua" line 181.
> By the way I don't use GPU. And it always return nil in "BatcherFileList:getBatch()", I fix that bug and rerun the example data with the demo config , it failed.
> 
> > /home/momo/torch/install/share/lua/5.1/nn/Select.lua:11: attempt to compare nil with number
> > stack traceback:
> > /home/momo/torch/install/share/lua/5.1/nn/Select.lua:11: in function </home/momo/torch/install/share/lua/5.1/nn/Select.lua:9>
> > [C]: in function 'xpcall'
> > /home/momo/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
> > /home/momo/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
> > ../model/optimizer/MyOptimizer.lua:183: in function 'opfunc'
> > /home/momo/torch/install/share/lua/5.1/optim/adam.lua:37: in function 'optimMethod'
> > ../model/optimizer/MyOptimizer.lua:212: in function 'trainBatch'
> > ../model/optimizer/MyOptimizer.lua:133: in function <../model/optimizer/MyOptimizer.lua:90>
> > ..//model/OneModel.lua:412: in main chunk
> > [C]: in function 'dofile'
> > ...momo/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
> > [C]: at 0x00405d50
> > WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
> > stack traceback:
> > [C]: in function 'error'
> > /home/momo/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
> > /home/momo/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
> > ../model/optimizer/MyOptimizer.lua:183: in function 'opfunc'
> > /home/momo/torch/install/share/lua/5.1/optim/adam.lua:37: in function 'optimMethod'
> > ../model/optimizer/MyOptimizer.lua:212: in function 'trainBatch'
> > ../model/optimizer/MyOptimizer.lua:133: in function <../model/optimizer/MyOptimizer.lua:90>
> > ..//model/OneModel.lua:412: in main chunk
> > [C]: in function 'dofile'
> > ...momo/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
> > [C]: at 0x00405d50

请问解决了吗...

**Comment by rajarshd** [comment]
Hi. Unfortunately, I am unable to maintain this lua codebase anymore. However I am working on a pytorch re-implmentation which I should be releasing soon. Sorry for the inconvenience.
